### ISSUE TITLE
Invalid API URL for Github Enterprise

### ISSUE THREAD

**Issue by fmunteanu** [sargsyan/github-notifier#16]
I have Github Enterprise configured to:
https://github.domain.com

Your service is looking for:
https://api.github.domain.com/notifications

But this URL does not exist. I presume I need to create a `api.github.domain.com` CNAME, but I need to point it to what actual Github Enterprise URL?

Log error:
```
2019-11-25 14:51:30 ERROR Failed to connect to https://api.github.domain.com/notifications
```

**Comment by fmunteanu** [comment]
I believe this is the offending line:
https://github.com/sargsyan/github-notifier/blob/master/github_notif#L158

In Github Enterprise, the proper notifications URL is:
https://github.domain.com/api/v3/notifications

Is it possible to release a fix for this?

**Comment by sargsyan** [comment]
Hi @fmunteanu,

If I am not mistaken all Github Enterprise Installations provide the API with "api" subdomain. That is why the conversion is done under the hood. The same is true for github.com (api.github.com). The same error message would be reported if the personal access token is not working. To check if the URL is correct for your setup, please open https://api.github.domain.com in the browser. If the resulting page is not 404 page then the URL is correct.

**Comment by fmunteanu** [comment]
@sargsyan, I get a 404 when I try to access teh URL. From the [Enterprise documentation](https://developer.github.com/enterprise/2.19/v3/), the actual URL is `https://github.domain.com/api/v3`. Only github.com has an `api` subdomain.

**Comment by sargsyan** [comment]
Hi @fmunteanu 

If you have installed the app with brew, please upgrade to the latest version.

```
brew upgrade sargsyan/github-notifier/github-notifier
github-notifier-install
```
