### ISSUE TITLE
Notification title renamed to GitHub Notifier

### ISSUE THREAD

**Issue by fmunteanu** [sargsyan/github-notifier#18]
Is it possible to have the notification title changed to `GitHub Notifier`?

![Screen Shot 2019-12-13 at 12 33 16 PM](https://user-images.githubusercontent.com/19806136/70819844-35f0bc00-1da5-11ea-988c-cf31f0b5c0a5.png)

**Comment by sargsyan** [comment]
I am afraid there is no easy way to do it with the installed application (without touching many things)
