### ISSUE TITLE
Documentation Errata

### ISSUE THREAD

**Issue by thoran** [sargsyan/github-notifier#22]
**Describe the bug**
The documentation, https://githubnotifier.net/documentation/configurations/, has `github-notifications-configure`, but should be `github-notifier-configure`.

**To Reproduce**
1. Go to 'https://githubnotifier.net/documentation/configurations/'
2. See error

**Expected behavior**
I want to see the correct command: `github-notifier-configure`.

**Comment by sargsyan** [comment]
Thanks for reporting. It's fixed now.
