### ISSUE TITLE
feature request: open notification in "notification view"

### ISSUE THREAD

**Issue by jbergstroem** [sargsyan/github-notifier#25]
**Is your feature request related to a problem? Please describe.**

<img width="1323" alt="Screen Shot 2020-06-21 at 11 40 11 AM" src="https://user-images.githubusercontent.com/176984/85228978-030f2c80-b3b5-11ea-95b5-3b07cea47320.png">

With github releasing their new notification interface, they introduced a notification view (see screenshot below) that lets you manage the state of the navigation.

I'm not quite sure how they enable it, but its likely doable.

By having this available, I can act on the notification in relation to what actually was said. The other route would be going to notifications and ticking it off, post view.

**Describe the solution you'd like**
Opening a notification via notification center leads to the event with a "notification view"

**Describe alternatives you've considered**
The alternative would be what exists today, plus having to go to the notifications screen, marking it as read.

**Comment by sargsyan** [comment]
I think it might be doable after the service will use GitHub API v4. I plan to migrate to v4 soon.

**Comment by jbergstroem** [comment]
It doesn't look too complicated actually; github adds a querystring which then gets removed from the url:
`https://github.com/nodejs/TSC/issues/886?notification_referrer_id=<referrer_id>%3D#issuecomment-652606526`

Gonna look into where this id comes from; but it definitely seems related to the logged in users session.

**Comment by sargsyan** [comment]
Thank you for the hint. Unfortunately, **<notification_referrer_id>** is not provided by the API. At least I could find it in the documentation for both v3 and v4 API-s. It seems that Github uses it only for its own frontend. I checked the page source and it seems that the ids are some Base64 encoded strings. I even tried to Base64 encode **id** and **node_id** fields that we get from API, but the results were not the expected **<notification_referrer_id>**

**Comment by sargsyan** [comment]
Since Github does not provide the notification_referrer_id with public API-s, this feature cannot be implemented. Hence I am closing this issue.
